"""
Symbol dictionary and formula templates.
Deterministic lookup — no model calls needed for these.
"""

# ── Symbol lookup table ──────────────────────────────────────────
SYMBOL_TABLE: dict[str, str] = {
    # 基础运算
    "加": "+",
    "减": "-",
    "乘": r"\times",
    "除": r"\div",
    "点乘": r"\cdot",
    "叉乘": r"\times",
    "正负": r"\pm",
    "负正": r"\mp",

    # 关系
    "等于": "=",
    "不等于": r"\neq",
    "大于等于": r"\geq",
    "小于等于": r"\leq",
    "远大于": r"\gg",
    "远小于": r"\ll",
    "约等于": r"\approx",
    "相似": r"\sim",
    "正比于": r"\propto",

    # 集合
    "属于": r"\in",
    "不属于": r"\notin",
    "子集": r"\subset",
    "真子集": r"\subsetneq",
    "并集": r"\cup",
    "交集": r"\cap",
    "空集": r"\emptyset",
    "全集": r"\Omega",
    "补集": r"^c",
    "任意": r"\forall",
    "存在": r"\exists",
    "不存在": r"\nexists",

    # 希腊字母 (常用)
    "alpha": r"\alpha",
    "beta": r"\beta",
    "gamma": r"\gamma",
    "delta": r"\delta",
    "epsilon": r"\varepsilon",
    "theta": r"\theta",
    "lambda": r"\lambda",
    "mu": r"\mu",
    "sigma": r"\sigma",
    "phi": r"\varphi",
    "omega": r"\omega",
    "Alpha": r"A",
    "Beta": r"B",
    "Gamma": r"\Gamma",
    "Delta": r"\Delta",
    "Theta": r"\Theta",
    "Lambda": r"\Lambda",
    "Sigma": r"\Sigma",
    "Phi": r"\Phi",
    "Omega": r"\Omega",

    # 微积分
    "偏导": r"\partial",
    "无穷": r"\infty",
    "正无穷": r"+\infty",
    "负无穷": r"-\infty",
    "积分": r"\int",
    "二重积分": r"\iint",
    "三重积分": r"\iiint",
    "线积分": r"\oint",
    "极限": r"\lim",
    "趋向": r"\to",
    "求和": r"\sum",
    "连乘": r"\prod",
    "导数": "'",
    "二阶导": "''",
    "n阶导": r"^{(n)}",

    # 线性代数
    "行列式": r"\det",
    "转置": r"^{\top}",
    "逆": r"^{-1}",
    "范数": r"\|\cdot\|",
    "内积": r"\langle \cdot, \cdot \rangle",
    "张量积": r"\otimes",
    "直和": r"\oplus",

    # 概率统计
    "期望": r"\mathbb{E}",
    "方差": r"\mathrm{Var}",
    "协方差": r"\mathrm{Cov}",
    "概率": r"\mathbb{P}",
    "独立同分布": r"\stackrel{\text{iid}}{\sim}",

    # 箭头
    "右箭头": r"\rightarrow",
    "左箭头": r"\leftarrow",
    "双向箭头": r"\leftrightarrow",
    "推出": r"\Rightarrow",
    "等价于": r"\Leftrightarrow",
    "映射到": r"\mapsto",

    # 装饰
    "上划线": r"\overline",
    "下划线": r"\underline",
    "帽子": r"\hat",
    "波浪": r"\tilde",
    "向量箭头": r"\vec",
    "上点": r"\dot",
    "上双点": r"\ddot",
    "横线": r"\bar",
    "宽帽子": r"\widehat",
    "宽波浪": r"\widetilde",

    # 括号
    "左大括号": r"\left\{",
    "右大括号": r"\right\}",
    "左中括号": r"\left[",
    "右中括号": r"\right]",
    "左小括号": r"\left(",
    "右小括号": r"\right)",
    "尖括号": r"\langle",
    "右尖括号": r"\rangle",
    "绝对值": r"|",
    "范数符号": r"\|",

    # 常用函数
    "sin": r"\sin",
    "cos": r"\cos",
    "tan": r"\tan",
    "log": r"\log",
    "ln": r"\ln",
    "exp": r"\exp",
    "max": r"\max",
    "min": r"\min",
    "sup": r"\sup",
    "inf": r"\inf",
    "limsup": r"\limsup",
    "liminf": r"\liminf",
    "argmin": r"\arg\min",
    "argmax": r"\arg\max",

    # 特殊
    "梯度": r"\nabla",
    "分段": r"\begin{cases}",
    "矩阵": r"\begin{pmatrix}",
    "省略号": r"\cdots",
    "竖省略": r"\vdots",
    "对角省略": r"\ddots",
    "因为": r"\because",
    "所以": r"\therefore",
    " qed": r"\blacksquare",
    "证毕": r"\blacksquare",
}

# ── Formula templates ────────────────────────────────────────────
TEMPLATES: dict[str, str] = {
    "euler": r"e^{i\pi} + 1 = 0",
    "欧拉公式": r"e^{i\theta} = \cos\theta + i\sin\theta",
    "勾股定理": r"a^{2} + b^{2} = c^{2}",
    "泰勒展开": r"f(x) = \sum_{n=0}^{\infty} \frac{f^{(n)}(a)}{n!}(x-a)^{n}",
    "二次公式": r"x = \frac{-b \pm \sqrt{b^{2}-4ac}}{2a}",
    "高斯积分": r"\int_{-\infty}^{\infty} e^{-x^{2}} dx = \sqrt{\pi}",
    "贝叶斯": r"P(A|B) = \frac{P(B|A)P(A)}{P(B)}",
    "期望定义": r"\mathbb{E}[X] = \sum_{i=1}^{n} x_i p_i",
    "方差定义": r"\mathrm{Var}(X) = \mathbb{E}[(X - \mu)^{2}]",
    "正态分布": r"f(x) = \frac{1}{\sigma\sqrt{2\pi}} e^{-\frac{(x-\mu)^{2}}{2\sigma^{2}}}",
    "柯西施瓦茨": r"|\langle u, v \rangle| \leq \|u\| \|v\|",
    "傅里叶变换": r"\hat{f}(\xi) = \int_{-\infty}^{\infty} f(x) e^{-2\pi i x \xi} dx",
    "拉普拉斯变换": r"F(s) = \int_{0}^{\infty} f(t) e^{-st} dt",
    "欧拉法": r"y_{n+1} = y_n + h f(x_n, y_n)",
    "叉积公式": r"\vec{a} \times \vec{b} = \begin{vmatrix} \vec{i} & \vec{j} & \vec{k} \\ a_1 & a_2 & a_3 \\ b_1 & b_2 & b_3 \end{vmatrix}",
    "链式法则": r"\frac{df(g(x))}{dx} = f'(g(x)) \cdot g'(x)",
    "分部积分": r"\int u\,dv = uv - \int v\,du",
    "格林公式": r"\oint_C (P\,dx + Q\,dy) = \iint_D \left(\frac{\partial Q}{\partial x} - \frac{\partial P}{\partial y}\right) dx\,dy",
    "斯托克斯定理": r"\oint_C \vec{F} \cdot d\vec{r} = \iint_S (\nabla \times \vec{F}) \cdot d\vec{S}",
    "散度定理": r"\iiint_V (\nabla \cdot \vec{F}) dV = \oiint_S \vec{F} \cdot d\vec{S}",
}

# ── Shorthand aliases (user-typable shortcuts) ───────────────────
SHORTHANDS: dict[str, str] = {
    "..": r"\cdots",
    "...": r"\cdots",
    "->": r"\rightarrow",
    "=>": r"\Rightarrow",
    "<-": r"\leftarrow",
    "<=>": r"\Leftrightarrow",
    "!=": r"\neq",
    ">=": r"\geq",
    "<=": r"\leq",
    "inf": r"\infty",
    "pi": r"\pi",
    "theta": r"\theta",
    "lambda": r"\lambda",
    "sigma": r"\sigma",
    "omega": r"\omega",
    "nabla": r"\nabla",
    "partial": r"\partial",
    "int": r"\int",
    "iint": r"\iint",
    "iiint": r"\iiint",
    "sum": r"\sum",
    "prod": r"\prod",
    "lim": r"\lim",
    "frac": r"\frac{}{}",
    "sqrt": r"\sqrt{}",
    "vec": r"\vec{}",
    "hat": r"\hat{}",
    "bar": r"\bar{}",
    "dot": r"\dot{}",
    "mat": r"\begin{pmatrix}  \\  \end{pmatrix}",
    "case": r"\begin{cases}  \\  \end{cases}",
}
