"""Test HistoryStore — SQLite database operations."""
import pytest
from texada.config import TeXadaConfig
from texada.store.history import HistoryStore
from texada.types import HistoryEntry


@pytest.mark.asyncio
async def test_history_basic(tmp_path):
    config = TeXadaConfig(data_dir=tmp_path)
    store = HistoryStore(config)

    entry = HistoryEntry(
        id=0,  # Auto-generated by SQLite
        input_text="二重积分 f(x,y)",
        input_type="text",
        latex="\\iint_D f(x,y)",
        intent="integral",
        source="model",
        render_mode="katex",
        valid=True,
        latency_ms=120.5,
        tokens_used=42,
        starred=False,
        created_at="",  # Auto-generated by SQLite
    )

    # Test adding entry
    inserted_id = await store.add(entry)
    assert inserted_id > 0

    # Test listing entries
    recent = await store.list_recent()
    assert len(recent) == 1
    assert recent[0].input_text == "二重积分 f(x,y)"
    assert recent[0].latex == "\\iint_D f(x,y)"
    assert recent[0].valid is True

    # Test querying entries
    query_match = await store.list_recent("f(x,y)")
    assert len(query_match) == 1

    query_no_match = await store.list_recent("sum")
    assert len(query_no_match) == 0


@pytest.mark.asyncio
async def test_history_cleanup(tmp_path):
    config = TeXadaConfig(data_dir=tmp_path)
    store = HistoryStore(config)

    entry = HistoryEntry(
        id=0,
        input_text="test",
        input_type="text",
        latex="test",
        intent="generic",
        source="model",
        render_mode="katex",
        valid=True,
        latency_ms=10.0,
        tokens_used=10,
        starred=False,
        created_at="",
    )

    await store.add(entry)

    # Run cleanup — should not delete anything as it's not older than 30 days
    deleted = await store.cleanup()
    assert deleted == 0

    recent = await store.list_recent()
    assert len(recent) == 1
