"""Test HistoryStore — SQLite database operations."""
import pytest

from texada.config import TeXadaConfig
from texada.store.history import HistoryStore
from texada.types import HistoryEntry


@pytest.mark.asyncio
async def test_history_basic(tmp_path):
    config = TeXadaConfig(data_dir=tmp_path)
    store = HistoryStore(config)

    entry = HistoryEntry(
        id=0,  # Auto-generated by SQLite
        input_text="二重积分 f(x,y)",
        input_type="text",
        latex="\\iint_D f(x,y)",
        intent="integral",
        source="model",
        render_mode="katex",
        valid=True,
        latency_ms=120.5,
        tokens_used=42,
        starred=False,
        created_at="",  # Auto-generated by SQLite
    )

    # Test adding entry
    inserted_id = await store.add(entry)
    assert inserted_id > 0

    # Test listing entries
    recent = await store.list_recent()
    assert len(recent) == 1
    assert recent[0].input_text == "二重积分 f(x,y)"
    assert recent[0].latex == "\\iint_D f(x,y)"
    assert recent[0].valid is True

    # Test querying entries
    query_match = await store.list_recent("f(x,y)")
    assert len(query_match) == 1

    query_no_match = await store.list_recent("sum")
    assert len(query_no_match) == 0


@pytest.mark.asyncio
async def test_history_query_searches_latex_and_filters_by_type(tmp_path):
    config = TeXadaConfig(data_dir=tmp_path)
    store = HistoryStore(config)

    await store.add(HistoryEntry(
        input_text="二重积分 f(x,y)",
        input_type="nl",
        latex="\\iint_D f(x,y)",
        intent="integral",
        source="model",
        render_mode="katex",
        valid=True,
        latency_ms=120.5,
    ))
    await store.add(HistoryEntry(
        input_text="\\sum_{i=1}^{",
        input_type="completion",
        latex="\\sum_{i=1}^{n} i",
        intent="completion",
        source="model",
        render_mode="katex",
        valid=True,
        latency_ms=30.0,
    ))

    completions = await store.list_recent("sum", input_type="completion")

    assert len(completions) == 1
    assert completions[0].input_type == "completion"
    assert completions[0].input_text == "\\sum_{i=1}^{"


@pytest.mark.asyncio
async def test_history_cleanup_enforces_max_items(tmp_path):
    config = TeXadaConfig(data_dir=tmp_path, history_max_items=2)
    store = HistoryStore(config)

    for input_text in ["first", "second", "third"]:
        await store.add(HistoryEntry(
            input_text=input_text,
            input_type="nl",
            latex=input_text,
            intent="generic",
            source="model",
            render_mode="katex",
            valid=True,
            latency_ms=10.0,
        ))

    recent = await store.list_recent()

    assert [entry.input_text for entry in recent] == ["third", "second"]


@pytest.mark.asyncio
async def test_history_cleanup(tmp_path):
    config = TeXadaConfig(data_dir=tmp_path)
    store = HistoryStore(config)

    entry = HistoryEntry(
        id=0,
        input_text="test",
        input_type="text",
        latex="test",
        intent="generic",
        source="model",
        render_mode="katex",
        valid=True,
        latency_ms=10.0,
        tokens_used=10,
        starred=False,
        created_at="",
    )

    await store.add(entry)

    # Run cleanup — should not delete anything as it's not older than 30 days
    deleted = await store.cleanup()
    assert deleted == 0

    recent = await store.list_recent()
    assert len(recent) == 1


@pytest.mark.asyncio
async def test_history_export_import_merge_and_clear(tmp_path):
    source = HistoryStore(TeXadaConfig(data_dir=tmp_path / "source"))
    target = HistoryStore(TeXadaConfig(data_dir=tmp_path / "target"))

    entry = HistoryEntry(
        input_text="integral",
        input_type="nl",
        latex="\\int x\\,dx",
        intent="integral",
        source="model",
        render_mode="katex",
        valid=True,
        latency_ms=10.0,
        created_at="2026-07-20 10:00:00",
    )

    await source.import_entries([entry])
    exported = await source.export_all()

    first = await target.import_entries(exported)
    second = await target.import_entries(exported)

    assert first == {"imported": 1, "skipped": 0, "cleared": 0}
    assert second == {"imported": 0, "skipped": 1, "cleared": 0}
    assert len(await target.export_all()) == 1
    assert await target.clear("nl") == 1
    assert await target.export_all() == []


@pytest.mark.asyncio
async def test_history_import_replace_clears_existing_rows(tmp_path):
    store = HistoryStore(TeXadaConfig(data_dir=tmp_path))

    await store.add(HistoryEntry(
        input_text="old",
        input_type="nl",
        latex="old",
        intent="generic",
        source="model",
        render_mode="katex",
        valid=True,
        latency_ms=1.0,
    ))

    result = await store.import_entries(
        [
            HistoryEntry(
                input_text="new",
                input_type="completion",
                latex="new",
                intent="completion",
                source="model",
                render_mode="latex",
                valid=True,
                latency_ms=2.0,
            )
        ],
        mode="replace",
    )

    entries = await store.export_all()
    assert result["cleared"] == 1
    assert [entry.input_text for entry in entries] == ["new"]
