"""Render the machine-readable CAS boundary as a reviewable Markdown table."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
MATRIX_PATH = ROOT / "eval" / "cas_capabilities.yaml"
DOC_PATH = ROOT / "docs" / "sympy-capability-matrix.md"


def render(matrix: dict[str, Any]) -> str:
    environment = matrix["environment"]
    acceptance = matrix["acceptance"]
    lines = [
        "# SymPy capability matrix",
        "",
        "<!-- Generated by scripts/render-cas-capabilities.py; "
        "edit eval/cas_capabilities.yaml. -->",
        "",
        matrix["description"].strip(),
        "",
        "## Locked environment",
        "",
        "| Component | Version | Pin |",
        "| --- | --- | --- |",
        f"| Python | {environment['python']} | — |",
        f"| KaTeX | {environment['katex']} | vendored |",
    ]
    for name in ("sympy", "antlr4-python3-runtime", "lark", "psutil"):
        item = environment[name]
        lines.append(f"| {name} | {item['version']} | `{item['pin']}` |")

    lines.extend(
        [
            "",
            "## Production Semantic Unit adapter",
            "",
            "| Case | Left | Right | Expected status | Evidence / rejection |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for case in matrix["semantic_adapter_cases"]:
        expected = case["expected"]
        evidence = expected.get("basis") or expected.get("reason_code") or "—"
        lines.append(
            "| {id} | `{lhs}` | `{rhs}` | {status} | `{evidence}` |".format(
                id=_escape(case["id"]),
                lhs=_escape(case["lhs"]),
                rhs=_escape(case["rhs"]),
                status=expected["status"],
                evidence=_escape(evidence),
            )
        )

    lines.extend(
        [
            "",
            "## Raw parser probes (evaluation only)",
            "",
            "These backends are not used by the production adapter. Parsed means only "
            "that the backend returned an object; warnings record known semantic drift.",
            "",
            "| Case | Backend | Strict | Outcome | Type / exception | Warning |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for case in matrix["raw_parser_probes"]:
        expected = case["expected"]
        result_type = expected.get("type") or expected.get("exception") or "—"
        warning = expected.get("semantic_warning") or "—"
        lines.append(
            "| {id} | {backend} | {strict} | {outcome} | `{result_type}` | "
            "`{warning}` |".format(
                id=_escape(case["id"]),
                backend=case["backend"],
                strict=str(case["strict"]).lower(),
                outcome=expected["outcome"],
                result_type=_escape(result_type),
                warning=_escape(warning),
            )
        )

    lines.extend(
        [
            "",
            "## SymPy contract probes",
            "",
            "| Case | Tier | Expected |",
            "| --- | --- | --- |",
        ]
    )
    for case in matrix["sympy_contract_probes"]:
        expected = ", ".join(
            f"{key}={value}" for key, value in case["expected"].items()
        )
        lines.append(
            f"| {_escape(case['id'])} | {case['tier']} | `{_escape(expected)}` |"
        )

    lines.extend(
        [
            "",
            "## Determinism probes",
            "",
            "| Case | Seed → expected result | Repetitions |",
            "| --- | --- | --- |",
        ]
    )
    for case in matrix["sympy_random_probes"]:
        outcomes = ", ".join(
            f"{seed}→{value}"
            for seed, value in case["expected_by_seed"].items()
        )
        lines.append(
            f"| {_escape(case['id'])} | `{_escape(outcomes)}` | "
            f"{case['repetitions']} |"
        )

    resources = matrix["worker_resources"]
    lines.extend(
        [
            "",
            "## Worker resource boundary",
            "",
            f"RSS is observed as **{resources['rss_unit']}** by "
            f"`{resources['rss_monitor']}`. `RLIMIT_AS` is not treated as the "
            "cross-platform authority. The default ceiling is "
            f"**{resources['default_max_rss_bytes']} bytes**, sampled every "
            f"**{resources['poll_interval_ms']} ms**.",
            "",
            "| Platform | RLIMIT_AS authority | Reason |",
            "| --- | --- | --- |",
        ]
    )
    for platform, details in resources["platforms"].items():
        lines.append(
            f"| {platform} | "
            f"{str(details['rlimit_as_authority']).lower()} | "
            f"`{_escape(details['reason'])}` |"
        )

    cache = matrix["cache"]
    lines.extend(
        [
            "",
            "## Cache identity",
            "",
            "The formula pair is ordered. Cache keys contain: "
            + ", ".join(f"`{field}`" for field in cache["key_fields"])
            + ".",
        ]
    )

    lines.extend(
        [
            "",
            "## Acceptance red lines",
            "",
            f"- Maximum observed false verified: "
            f"**{acceptance['maximum_false_verified']}**.",
            f"- Unsupported input reaches the comparator: "
            f"**{str(acceptance['unsupported_reaches_comparator']).lower()}**.",
            f"- Verified requires an evidence basis: "
            f"**{str(acceptance['verified_requires_basis']).lower()}**.",
            f"- Verified always exposes assumptions: "
            f"**{str(acceptance['verified_requires_assumptions_field']).lower()}**.",
            f"- Verified always exposes the task seed: "
            f"**{str(acceptance['verified_requires_seed']).lower()}**.",
            f"- Verified always exposes the policy version: "
            f"**{str(acceptance['verified_requires_policy_version']).lower()}**.",
            "",
            "The zero-false-verified threshold applies to this pinned matrix, not to all "
            "possible mathematics. Coverage may expand only by adding cases and preserving "
            "that threshold.",
            "",
        ]
    )
    return "\n".join(lines)


def _escape(value: Any) -> str:
    return str(value).replace("|", r"\|").replace("`", r"\`").replace("\n", " ")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated document is not up to date",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="print the generated document without writing it",
    )
    args = parser.parse_args()

    matrix = yaml.safe_load(MATRIX_PATH.read_text(encoding="utf-8"))
    rendered = render(matrix)
    if args.stdout:
        print(rendered, end="")
        return 0
    if args.check:
        current = DOC_PATH.read_text(encoding="utf-8") if DOC_PATH.exists() else ""
        if current != rendered:
            print(
                "docs/sympy-capability-matrix.md is stale; run "
                "python scripts/render-cas-capabilities.py"
            )
            return 1
        return 0
    DOC_PATH.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
